[project]
name = "learn-deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "macbook pro 16", email = "glimmer.treasure@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "torch>=2.14.1",
]

[project.scripts]
mini-transformer = "mini_transformer:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "notebook>=7.6.3",
]
